name: Build and Package IPA

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up environment
        run: |
          set -e
          echo "Building IPA"
      
      - name: Build with Xcode
        run: |
          xcodebuild clean build -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO"
          echo "done building"
      
      - name: Process with RootHelperSample
        run: |
          cd RootHelperSample
          ldid -Sentitlements.plist -Cadhoc ../usprebooter/ldid
          ldid -Sentitlements.plist -Cadhoc ../usprebooter/fastPathSign
          gmake -j$(sysctl -n hw.ncpu)
          ldid -Sentitlements.plist -Cadhoc .theos/obj/debug/arm64/trolltoolsroothelper
          mv .theos/obj/debug/arm64/trolltoolsroothelper ../build/Release-iphoneos/usprebooter.app/trolltoolsroothelper
      
      - name: Package IPA
        run: |
          cd ../build/Release-iphoneos
          rm -rf Payload FUCK.tipa
          mkdir Payload
          cp -r usprebooter.app Payload
          ldid -S ../../ent.plist -Cadhoc Payload/usprebooter.app/usprebooter
          zip -vr FUCK.tipa Payload/ -x "*.DS_Store"
